name: Generate-Fancy-Snake-Header

on: 
  push:
  schedule: # execute every day at 11PM EST
    - cron: '00 23 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Animate snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master # Snake animation
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3 # Deploy to output branch
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}